# language: node_js
# node_js:
#  - "node"
# install: npm install

language: node_js
node_js:
  - "12.14.1"

install: yarn install

# after_success:
#   - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

script: echo "Running tests against $(node -v)... Running Jest test and coverage below and sending it to coveralls!"

jobs:
  include:
    - stage: Produce Coverage
      node_js: "12.14.1"
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
